version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: pgdatabase    
    volumes:
      - pgdata-volume:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pgadmin
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=nelson8000@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2019!            
volumes:
  pgdata-volume:
    external: true